### PR TITLE
Honestly, how hard is it?

### PR DESCRIPTION
**Pull request by ItsHarry**
It's been 1.5 years since UUIDs were officially announced, it's been 6 months since namechanges were released, and still no proper UUID support.

Why do the customers have to fix everything themselves?

### CODE REVIEW

**Comment by LeeMcNeil** [comment]
Hi, have you looked at version 6.8 released on Twitter? We have already added everything which you have committed here.

**Comment by ItsHarry** [comment]
Buycraft-v6.8-beta-2.jar, correct? That one does not work.

```java
[Buycraft] This server must be in online mode
```

If you decompile the plugin, you will see that there are "Bukkit.getOnlineMode()" calls everywhere, which will always return false, because BungeeCord requires you to use offline mode.

I'm pretty sure the beta build you uploaded on Twitter is the exact same as on GitHub.

**Comment by LeeMcNeil** [comment]
Yes that's correct, our developer is currently away till tomorrow, let me push this past him and I will get back to you ASAP. Could you confirm that your PR is working for you?

**Comment by ItsHarry** [comment]
Yes, it's working fine.

**Comment by mrminecart** [comment]
Thank you for your help in solving the matter. We have taken your concept and applied it where needed. We have kept the old configuration key 'isBungeecord' to ensure backwards compatibility.

**Pull request closed without merging**
